site_id: guides

theme: iiifc-theme
title: IIIF Resource Guides
permalink:      pretty
root_url:       'https://preview.iiif.io/root/wireframe'
api_url:        'https://preview.iiif.io/api/wireframe/api'
cookbook_url:   'https://preview.iiif.io/cookbook/wireframe'
guides_url:   ''

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

plugins:
  - jekyll-last-modified-at

notification:
  enabled: true
  title: This website design is in pre-beta.
  subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  link: '#'
  link_label: This is a test link
